name: .NET CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore WebApplication1Test/WebApplication1Test.csproj
      
      # If you suspect some packages might still be missing after restore, add this step
      - name: Install missing packages
        run: |
          dotnet list WebApplication1Test/WebApplication1Test.csproj package > packageList.txt
          grep 'warning' packageList.txt | while read -r line ; do
            missingPackage=`echo $line | cut -d' ' -f2`
            missingVersion=`echo $line | cut -d' ' -f4`
            dotnet add WebApplication1Test/WebApplication1Test.csproj package $missingPackage --version $missingVersion
          done

      - name: Build
        run: dotnet build WebApplication1Test/WebApplication1Test.csproj --no-restore -c Release

      - name: Test
        run: dotnet test WebApplication1Test/WebApplication1Test.csproj --no-build --verbosity normal

      - name: Publish
        run: dotnet publish WebApplication1Test/WebApplication1Test.csproj --no-build -c Release -o publish

      - name: Build Docker image
        run: docker build -t yourappname:$(date +%s) .
    
    # Add your Docker Hub login and push steps as before
